### ISSUE TITLE
The new version of DS4 on Strix-halo seems to not work properly

### ISSUE THREAD

**Issue by maxben65** [antirez/ds4#577]
Hi,
The new version of ds4 on Strix-Halo doesn't seem to work properly.
When sending the simple "ciao chi sei?" prompt to the previous version, ds4 correctly responded with "Ciao! Sono DeepSeek....".
With the new version, however, it seems to be thinking in "Chinese" and doesn't send any response.
See below.

Thanks anyway for the great work.
Massimo

### previous version (2026-06-16)

 ./ds4
ds4: Linux rocm backend set oom_score_adj=1000
ds4: ROCm backend initialized on AMD Radeon Graphics (sm_115)
ds4: ROCm preparing model tensor mappings: 80.24 GiB
ds4: ROCm startup model preparation covered 80.76 GiB of tensor spans in 20.354s
ds4: rocm backend initialized for graph diagnostics
ds4: context buffers 1053.75 MiB (ctx=32768, backend=rocm, prefill_chunk=4096, raw_kv_rows=4352, compressed_kv_rows=8194)
Commands:
  /help          Show this help.
  /think         Use normal thinking mode.
  /think-max     Use Think Max only when context is at least 393216 tokens.
  /nothink       Disable thinking mode.
  /ctx N         Set context size for following prompts.
  /power N       Set GPU duty cycle percentage, 1..100.
  /read FILE     Read a prompt from FILE and run it.
  /quit, /exit   Leave the prompt.
  Ctrl+C         Stop generation and return to the prompt.
**ds4> ciao chi sei?**
_processing 14 input tokens: 14/14 (100.0%)
Hmm, the user greeted me in Italian with "ciao chi sei?" which means "hello who are you?" This is a common introductory question. I should respond in Italian since the user initiated in that language. I need to clearly state my identity as an AI assistant, mention my creator company, and express my readiness to help. Keeping it friendly and open-ended will invite further conversation. I'll use simple Italian sentences without unnecessary details._
**Ciao! Sono DeepSeek, un assistente AI creato da DeepSeek. Sono qui per aiutarti con domande, informazioni, risolvere problemi e conversare in modo amichevole. Come posso esserti utile oggi?**
ds4: prefill: 6.42 t/s, generation: 16.44 t/s
ds4>

### new version (2026-07-20)
./ds4
ds4: Linux rocm backend set oom_score_adj=1000
ds4: ROCm backend initialized on AMD Radeon Graphics (sm_115)
ds4: ROCm preparing model tensor mappings: 80.24 GiB
ds4: ROCm startup model preparation covered 80.76 GiB of tensor spans in 20.858s
ds4: rocm backend initialized for graph diagnostics
ds4: memory: KV 0.78 GiB (raw 0.36 + compressed 0.42) + buffers 0.25 GiB + resident model 80.76 GiB = 81.79 GiB planned
ds4: memory detail: ctx=32768 prefill_cap=4096 raw_kv_rows=4352 compressed_kv_rows=8194 backend=rocm
ds4: memory: KV 0.78 GiB (raw 0.36 + compressed 0.42) + buffers 0.25 GiB = 1.03 GiB context
ds4: memory detail: ctx=32768 prefill_cap=4096 raw_kv_rows=4352 compressed_kv_rows=8194 backend=rocm
Commands:
  /help          Show this help.
  /think         Use normal thinking mode.
  /think-max     Use Think Max only when context is at least 393216 tokens.
  /nothink       Disable thinking mode.
  /ctx N         Set context size for following prompts.
  /power N       Set GPU duty cycle percentage, 1..100.
  /read FILE     Read a prompt from FILE and run it.
  /quit, /exit   Leave the prompt.
  Ctrl+C         Stop generation and return to the prompt.
**ds4> ciao chi sei?**
_processing 14 input tokens: 14/14 (100.0%)
鬼谷八荒吧 关注：402,303贴子：3,452,439
各位道友，我想请教一下，有没有办法更改已经刷出来的逆天改命啊
各位道友，我想请教一下，有没有办法更改已经刷出来的逆天改命啊，我用修改器修改后，只改变了一个名字，但效果还是原来的，比如我把三级剑痴改成了三级小李飞剑，结果效果还是剑痴的效果。有没有办法更改呢，求告知，谢
  各位道友
开修改器改天赋啊
可以改，但必须是同种类的，比如，你原本是三级剑痴，你想换成三级小李飞剑，都是三级，同种类，可以用修改器改，但必须是同一种类，比如都是攻击类的，或者都是防御类的。
创意工坊有一个mod可以让你每次突破时都能重选逆天改命，或者开局就可以选更多。
用修改器直接改就行了，用那个添加修改，把原来的删了，加一个新的_
ds4: prefill: 37.99 t/s, generation: 9.31 t/s
ds4>

**Comment by manrico-sessa** [comment]
I can reproduce the same ROCm inference regression on a second Strix Halo system.

## Environment

* System: GMKtec NucBox EVO-X2
* APU: AMD Ryzen AI Max+ 395
* GPU: AMD Radeon 8060S Graphics
* ROCm architecture: `gfx1151`
* DS4 reports the backend as `sm_115`
* 128 GB unified memory
* Ubuntu 26.04
* build command:

```bash
make clean
make strix-halo -j"$(nproc)"
```

## Model verification

I am using the official DeepSeek V4 Flash imatrix GGUF:

```text
DeepSeek-V4-Flash-IQ2XXS-w2Q2K-AProjQ8-SExpQ8-OutQ8-chat-v2-imatrix.gguf
```

File size:

```text
86720111488 bytes
```

SHA-256:

```text
efc7ed607ff27076e3e501fc3fefefa33c0ed8cf1eff483a2b7fdc0c2e616668
```

The same GGUF was used for every commit tested.

## Commit results

The most recent commit that I verified as working correctly on ROCm/Strix Halo is:

```text
519c4d8fe71a67bc80bba6e7b034d0dadc2114b5
Fix PRO streaming and sampling correctness
```

At `519c4d8`, the model answers the test prompt correctly.

The first compilable commit that I verified as producing corrupted logits is:

```text
ef8d923ad7290ef0b93dd26a364bdb048ab4428a
Add ROCm GLM 5.2 support
```

The following later commits are also affected:

```text
a185c36  Stabilize CUDA and Metal session batching
e0824dd  Make release builds warning-free
427e281  Optimize Metal prefill and decode kernels
efdadd4  README: update the AI assisted models list
```

The exact `main` commit tested was:

```text
efdadd41e20134af4f3381e1ed90e96fe4faef6f
```

The direct parent of `ef8d923` is:

```text
66cbce52896baa14df52e6d18cfc3fcb8f0bc537
Unify distributed inference CLI and documentation
```

However, `66cbce5` cannot be classified because `make strix-halo` fails to compile it.

The build errors include:

```text
conflicting types for 'ds4_gpu_routed_moe_one_tensor'

redefinition of:
  ds4_gpu_signal_selected_readback_ready
  ds4_gpu_commit_and_wait_selected_readback
  ds4_gpu_wait_selected_readback_ready
```

Therefore, the precise conclusion is:

```text
last verified good commit:       519c4d8
first testable bad commit:       ef8d923
exact first bad commit:          not proven
unbuildable commit in between:   66cbce5
```

## Minimal reproduction on ef8d923 and efdadd4

```bash
MODEL="/home/manrico/models/ds4/gguf/DeepSeek-V4-Flash-IQ2XXS-w2Q2K-AProjQ8-SExpQ8-OutQ8-chat-v2-imatrix.gguf"

./ds4 \
  --rocm \
  -m "$MODEL" \
  --ctx 32768 \
  --nothink \
  --temp 0 \
  -n 32 \
  -p "Rispondi in italiano con una sola frase: qual è la capitale d'Italia?"
```

Expected result:

```text
La capitale d'Italia è Roma.
```

Actual result on `ef8d923`, `a185c36`, `e0824dd`, `427e281` and `efdadd4`:

```text
激package com.example.demo;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.GetMapping
```

The failure occurs:

* with the standard 32768-token context;
* without any custom launcher;
* without an explicit `--prefill-chunk`;
* with deterministic greedy decoding using `--temp 0`;
* after `make clean`;
* after rebuilding with `make strix-halo`;
* with the official GGUF and its verified SHA-256.

## Tokenization and logprob evidence

`--dump-tokens` reconstructs the Italian input prompt correctly.

However, `--dump-logprobs` shows that the first generated token is already unrelated to the prompt:

```json
{
  "step": 0,
  "selected": {
    "id": 3934,
    "text": "激",
    "bytes": [230, 191, 128]
  },
  "logit": 13.3970661,
  "logprob": -2.5242393
}
```

The other highest-ranked candidates at step zero are also unrelated Chinese tokens.

After the first wrong token, the logits become strongly biased toward a Java/Spring Boot continuation. Tokens such as:

```text
package
import
.springframework
.boot
Application
```

are then selected with very high confidence.

This indicates that the problem is already present in the logits and is not caused by sampling randomness or by the prompt tokenizer.

## Bisect summary

The automated test classified commits as follows:

```text
519c4d8  GOOD
66cbce5  SKIP — does not compile with make strix-halo
ef8d923  BAD
a185c36  BAD
e0824dd  BAD
427e281  BAD
efdadd4  BAD
```

Several additional intermediate commits were skipped because they did not compile with the Strix Halo target.

## Working workaround

Until the ROCm regression is fixed, the latest commit that I have verified as working is:

```text
519c4d8fe71a67bc80bba6e7b034d0dadc2114b5
```

A temporary workaround is to check out that exact commit and rebuild:

```bash
cd "$HOME/Tools/ds4"

git fetch origin

git switch --detach \
  519c4d8fe71a67bc80bba6e7b034d0dadc2114b5

make clean
make strix-halo -j"$(nproc)"
```

Then verify the restored build:

```bash
./ds4 \
  --rocm \
  -m ./ds4flash.gguf \
  --ctx 32768 \
  --nothink \
  --temp 0 \
  -n 32 \
  -p "Rispondi in italiano con una sola frase: qual è la capitale d'Italia?"
```

On my system, `519c4d8` produces a correct answer, while `ef8d923` and `efdadd4` produce corrupted output.

To keep the working commit on a named local branch instead of remaining in detached HEAD:

```bash
git switch -c rocm-stable-519c4d8
```

This is only a rollback workaround. It does not fix the regression introduced somewhere between `519c4d8` and the first testable bad commit `ef8d923`.

## Additional ROCm test-build limitation

On this ROCm-only system, the documented command:

```bash
make test
```

tries to execute:

```text
/usr/local/cuda/bin/nvcc
```

and fails because the generic test target selects the CUDA build path.

For that reason I could not build and run `ds4_test --logprob-vectors` through the documented `make test` target. I instead collected:

* complete token dump;
* complete top-logprob JSON;
* generated output;
* Strix Halo build logs;
* Git bisect transcript.

I can provide all these files and test candidate ROCm patches on the Radeon 8060S / `gfx1151` system.

**Comment by maks** [comment]
A small update, I just built current master (efdadd41e20134af4f3381e1ed90e96fe4faef6f) and this is happening with even the test prompt in english:

```
 ./ds4 -p "Explain Redis streams in one paragraph."
ds4: Linux rocm backend set oom_score_adj=1000
ds4: ROCm backend initialized on AMD Radeon 8060S Graphics (sm_115)
ds4: ROCm preparing model tensor mappings: 80.24 GiB
ds4: ROCm startup model preparation covered 80.76 GiB of tensor spans in 27.079s
ds4: rocm backend initialized for graph diagnostics
ds4: memory: KV 0.78 GiB (raw 0.36 + compressed 0.42) + buffers 0.25 GiB + resident model 80.76 GiB = 81.79 GiB planned
ds4: memory detail: ctx=32768 prefill_cap=4096 raw_kv_rows=4352 compressed_kv_rows=8194 backend=rocm
ds4: memory: KV 0.78 GiB (raw 0.36 + compressed 0.42) + buffers 0.25 GiB = 1.03 GiB context
ds4: memory detail: ctx=32768 prefill_cap=4096 raw_kv_rows=4352 compressed_kv_rows=8194 backend=rocm
processing 16 input tokens: 16/16 (100.0%)
化package.json 配置文件的 main 字段中，我们通常会看到以下格式：
json
{
    "main": "lib/index.js"
}

我们也可以使用以下格式：
json
{
    "main": "lib/index"
}

或者
json
{
    "main": "lib"
}

这些配置分别代表什么意思呢？

## 解释

对于 `require('xxx')`，它会加载 package.json 中的 `main` 字段对应的文件。
如果 `main` 字段是 `lib/index.js`，则加载 `lib/index.js`。
如果 `main` 字段是 `lib/index`，则首先加载 `lib/index.js`，如果不存在则加载 `lib/index.json`，如果还是不存在则加载 `lib/index.node`。
如果 `main` 字段是 `lib`，则首先加载 `lib.js`，如果不存在则加载 `lib.json`，如果还是不存在则加载 `lib.node`，最后加载 `lib/index.js`，如果还不存在则加载 `lib/index.json`，如果还是不存在则加载 `lib/index.node`。
ds4: prefill: 37.74 t/s, generation: 8.56 t/s
```

Edit: I removed the markdown inside the response to not break the formatting inside this comment.

and can likewise confirm that building  `519c4d8fe71a67bc80bba6e7b034d0dadc2114b5` and running same test prompt as above works fine:
```
 ./ds4 -p "Explain Redis streams in one paragraph."
ds4: Linux rocm backend set oom_score_adj=1000
ds4: ROCm backend initialized on AMD Radeon 8060S Graphics (sm_115)
ds4: ROCm preparing model tensor mappings: 80.24 GiB
ds4: ROCm startup model preparation covered 80.76 GiB of tensor spans in 23.816s
ds4: rocm backend initialized for graph diagnostics
ds4: context buffers 1053.75 MiB (ctx=32768, backend=rocm, prefill_chunk=4096, raw_kv_rows=4352, compressed_kv_rows=8194)
processing 16 input tokens: 16/16 (100.0%)
We need to explain Redis streams in one paragraph. Keep it concise, covering key features: log-based data structure, append-only, consumer groups, blocking reads, etc.
Redis Streams is a log-based, append-only data structure within Redis that enables persistent, ordered sequences of events, supporting consumer groups for distributed message processing, blocking reads for real-time consumption, and optional non-blocking reads, all while leveraging Redis’s in-memory performance and optional persistence to handle high-throughput streaming workloads such as event sourcing, message queues, and real-time analytics.
ds4: prefill: 7.65 t/s, generation: 15.45 t/s
```

**Comment by yassineimounachen** [comment]
Spent $20 on tokens to tell you that `DS4_METAL_DISABLE_BATCH_HC_NORM_FUSION=1` fixes the nonsensical output. As for the decode speed that is related to `--quality` being forced or something of the sort.

**Comment by yassineimounachen** [comment]
Here is a patch that restores speed and correctness (no guarantees as to explaining mecanisms)

[fix-rocm-regression.patch](https://github.com/user-attachments/files/30234695/fix-rocm-regression.patch)

**Comment by olac-acul** [comment]
> Here is a patch that restores speed and correctness (no guarantees as to explaining mecanisms)
> 
> [fix-rocm-regression.patch](https://github.com/user-attachments/files/30234695/fix-rocm-regression.patch)

Thanks this solved for Deepseek. The problem is that it broke the GLM 5.2 inference: if you try to run it, it gives the same problem it gave to Deepseek without the patch

**Comment by centralscrutinizer21** [comment]
exactly how do you apply that patch?

**Comment by olac-acul** [comment]
> exactly how do you apply that patch?

You should execute "git apply fix-rocm-regression.patch" after putting patch file in your ds4 folder. Then recompile

**Comment by centralscrutinizer21** [comment]
Thank you

Il 25 luglio 2026 01:20:35 CEST, olac ***@***.***> ha scritto:
>olac-acul left a comment (antirez/ds4#577)
>
>> exactly how do you apply that patch?
>
>You should execute "git apply fix-rocm-regression.patch" after putting patch file in your ds4 folder. Then recompile
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/antirez/ds4/issues/577#issuecomment-5075476550
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
The Central Scrutinizer

**Comment by Schattenbanane** [comment]
Confirming this on a second Strix Halo machine, plus some localisation that
might narrow it down.

**Short version:** the corrupted output comes from the batched prefill path, not
from decode. `DS4_METAL_DISABLE_BATCH_HC_NORM_FUSION=1` fixes it — it works on
the ROCm backend despite the `METAL` name — at the cost of roughly 6x prefill
throughput. Without it, only `--prefill-chunk 1` is correct; every batch size
\>= 2 is wrong, in both prefill implementations.

### System

- Bosgame BeyondMax Series, baseboard AXB35-02, AMI BIOS 1.07 (2025-09-12)
- AMD Ryzen AI MAX+ 395 / Radeon 8060S Graphics (gfx1151, sm_115), 128 GB
  unified, 124 GiB GTT
- Fedora 44 Server, kernel 7.1.4-204.fc44.x86_64, linux-firmware-20260622
- ROCm 7.2.4, hipBLAS 3.2.70204, hipBLASLt 1.2.70204
- Binaries from `kyuz0/strix-halo-ds4-toolbox:rocm-7.2.4`, built 2026-07-23 from
  the `rocm` branch — exact commit not determined, but the image is public if you
  want to pin it
- `DeepSeek-V4-Flash-IQ2XXS-w2Q2K-AProjQ8-SExpQ8-OutQ8-chat-v2-imatrix.gguf`
  (80.76 GiB)
- Kernel cmdline `amd_iommu=off`; `ttm pages_limit=page_pool_size=32505856`

Full `--trace` and `--dump-logprobs` output attached.

### Reproducing

Model is the standard `./download_model.sh q2-imatrix` target. Everything below
ran inside the container image above; `$M` is the in-container model path:

```
M=/models/DeepSeek-V4-Flash-IQ2XXS-w2Q2K-AProjQ8-SExpQ8-OutQ8-chat-v2-imatrix.gguf

# wrapper used for every ds4run invocation below
ds4run() { podman run --rm \
  --device /dev/kfd --device /dev/dri --group-add video --group-add render \
  --security-opt seccomp=unconfined --security-opt label=disable \
  -v $HOME/ds4/models:/models:ro -v $HOME/ds4/trace:/trace \
  -e PATH=/usr/local/bin:/opt/rocm/bin:/usr/bin:/usr/sbin:/bin:/sbin \
  docker.io/kyuz0/strix-halo-ds4-toolbox:rocm-7.2.4 bash -lc "$*"; }
```

On a native build the same commands work with `./ds4` and a local GGUF path;
nothing here depends on the container beyond `--security-opt label=disable`,
which is only needed because SELinux otherwise blocks `/dev/kfd` (see the last
section).

The exact commands behind each piece of evidence below:

```
# correct reference
ds4run "ds4 --cpu  -m $M --nothink --temp 0 -p 'Explain mmap in C' -n 20"

# broken (default prefill_cap=4096)
ds4run "ds4 --rocm -m $M --nothink --temp 0 -p 'Explain mmap in C' -n 20"

# workaround
ds4run "DS4_METAL_DISABLE_BATCH_HC_NORM_FUSION=1 ds4 --rocm -m $M \
  --nothink --temp 0 -p 'Explain mmap in C' -n 20"

# chunk bisect
for C in 1 2 8 32 128 512 2048; do ds4run "ds4 --rocm -m $M \
  --prefill-chunk $C --nothink --temp 0 -p 'Explain mmap in C' -n 20"; done

# decode vs fresh-prefill logits
ds4run "ds4 --rocm -m $M --decode-consistency 8 -p 'Explain mmap in C'"

# CPU-vs-GPU whole-prompt logits
ds4run "ds4 --rocm -m $M --metal-graph-prompt-test -p 'Explain mmap in C'"

# attached logprobs dump
ds4run "ds4 --rocm -m $M --nothink --temp 0 --logprobs-top-k 20 \
  --dump-logprobs /trace/logprobs-broken.json -p 'Explain mmap in C'"

# attached server trace (run detached, one request, then stop)
ds4-server --rocm -m $M --ctx 32768 --host 0.0.0.0 --port 8000 \
  --trace /trace/ds4-577.txt

# quality comparison, matched token counts
# (ppl.txt is ~8 KB of arbitrary technical prose - only needs to be identical
#  across the two runs, the absolute value is not meaningful on its own)
ds4run "ds4 --rocm -m $M --ctx 32768 --tokens 1834 --perplexity-file /models/ppl.txt"
```

### Observed behaviour

Greedy, `--nothink`, 14-token prompt, same GGUF throughout.

CPU reference — correct:

```
$ ds4 --cpu -m $M --nothink --temp 0 -p 'Explain mmap in C' -n 20
`mmap` (memory map) is a powerful system call in C that creates a mapping of
ds4: prefill: 0.58 t/s, generation: 1.48 t/s
```

ROCm, default `prefill_cap=4096` — wrong:

```
$ ds4 --rocm -m $M --nothink --temp 0 -p 'Explain mmap in C' -n 20
ds4: using GPU graph generation with graph prefill
ds4: gpu prefill layer 43/43
波Irregular verbs are verbs that do not follow the standard
```

ROCm with the fusion disabled — correct, and byte-identical to the CPU path:

```
$ DS4_METAL_DISABLE_BATCH_HC_NORM_FUSION=1 ds4 --rocm -m $M --nothink --temp 0 \
    -p 'Explain mmap in C' -n 20
`mmap` (memory map) is a powerful system call in C that creates a mapping of
ds4: prefill: 5.97 t/s, generation: 10.03 t/s
```

The prefill cost of the workaround is the notable part: this build does ~38 t/s
prefill with the fusion on (and wrong output), ~6 t/s with it off.

### What the trace and logprobs show




Attached: [ds4-577.txt](https://github.com/user-attachments/files/30373008/ds4-577.txt) (server `--trace`) and [logprobs-broken.json](https://github.com/user-attachments/files/30373009/logprobs-broken.json)
(`ds4 --rocm --nothink --temp 0 --logprobs-top-k 20 --dump-logprobs`).

First, the rendered prompt is correct, so this is not a template or tokenizer
problem:

```
prompt_tokens: 9
think_mode: none
--- rendered prompt ---
<｜begin▁of▁sentence｜><｜User｜>Explain mmap in C<｜Assistant｜></think>
```

The generation from that prompt is a coherent academic abstract on an unrelated
subject — a Chinese title followed by fluent English prose about the global
distribution of warm-water coral reefs. Well-formed text, no relation to the
prompt whatsoever.

The logprobs dump quantifies why. At step 0:

- top-1 is token 4229 `波`, logprob -3.5213, i.e. **p = 2.96%**
- **all 20** of the top-20 candidates are CJK
- the logit spread across the whole top-20 is only **1.85** (12.19 -> 10.34)
- the entire top-20 accounts for just **19.5% of the probability mass** — the
  other ~80% is spread over the remaining ~129,260 tokens. By step 50 of the
  same generation the top-20 holds 100.0%.

(These are full-vocabulary log-softmax values: `logit - logprob` is a constant
15.7065 within the step, i.e. the log-sum-exp normaliser.)

That is a near-uniform distribution over unrelated Chinese characters. For
contrast, `--first-token-test` (exact CPU whole-model pass, same prompt) gives
top logit 16.77 for `#` with the runner-up at 15.82 — a clear peak, on tokens
plausible for the prompt.

Across all 113 generated steps, however, the mean top-1 probability is
**76.19%**, with only 4 steps below 10%. So decode is healthy and confident; it
is simply conditioned on nothing. It samples an essentially arbitrary first
token and then writes a fluent document from it. That looks more like prefill
leaving the state unconditioned than subtly perturbing it.

Supporting that: the two attachments generate *different* unrelated documents.
The server run (9-token prompt) produced the coral-reef abstract; the CLI run
(14-token prompt) produced "Irregular verbs are verbs that do not follow the
standard pattern of conjugation..." — the same continuation the chunk >= 32 runs
give. Two variables differ at once there (server vs CLI, 9 vs 14 tokens) so I
cannot attribute it cleanly, but a tiny prompt change yielding a completely
different coherent document fits "the state carries no prompt information"
better than "the state is perturbed".

Minor aside: the CLI renders this prompt as 14 tokens where the server renders
9. Presumably different templates — mentioning it only in case it is not
intentional.

### Chunk bisect — it is the batch dimension, not chunk stitching

Same prompt, `--nothink --temp 0`, varying `--prefill-chunk`:

| chunk | code path logged | output |
| ----- | ---------------- | ------ |
| 1 | `chunked GPU prefill` | **correct** |
| 2 | `chunked GPU prefill` | ` </think>I'm sorry, but I need more context to` |
| 8 | `chunked GPU prefill` | `####...# Diablo3 Item` |
| 32 | `gpu prefill layer 43/43` | `波Irregular verbs are verbs that do not follow the standard` |
| 128 | `gpu prefill layer 43/43` | identical to 32 |
| 512 | `gpu prefill layer 43/43` | identical to 32 |
| 2048 | `gpu prefill layer 43/43` | same, `波Irregular verbs ...` (prefill 7.06 t/s, gen 10.17 t/s) |
| 4096 (default) | `gpu prefill layer 43/43` | same |

Three observations:

1. 32/128/512 are all >= the 14-token prompt, so they run single-pass, and they
   log a **different** code path (`gpu prefill layer 43/43`) from 1/2/8
   (`chunked GPU prefill`). Both paths are wrong for batch > 1.
2. The prompt already fits one chunk at the 4096 default, so chunk stitching is
   not involved.
3. 32/128/512 produce byte-identical output beginning with token 4229 `波`,
   so it is deterministic rather than a race or an uninitialised read.

### --decode-consistency, default (broken) build

```
ds4: decode-consistency compared prefix_tokens=22 vocab=129280
     max_abs=33.3609772 at token=1 live=15.5075388 fresh=-17.8534374 rms=5.91323651
ds4: live_top:  {".w"}@27.978 {"."}@25.9794 {".t"}@25.1658 {".d"}@24.2365 {".s"}@24.1782 ...
ds4: fresh_top: {"波"}@12.8764 {"精"}@11.9527 {"防"}@11.8675 {"自"}@11.6012 {"方"}@11.556 ...
```

Incremental decode produces ASCII source-code tokens; a fresh full prefill of
the same prefix produces CJK. Divergence is at token 1, and `fresh_top[0]` is
the same token 4229 the chunk >= 32 runs emit.

`--metal-graph-prompt-test` with the fusion disabled, for a healthy reference on
this hardware:

```
tokens=14 logits_max=3.23252 logits_rms=0.696128
cpu_top=2581 gpu_top=2581 cpu_top_logit=30.2783 gpu_top_logit=29.7602
```

### Likely in-repo reproducer

The README says the C runner pins `DS4_METAL_PREFILL_CHUNK=2048` for the strict
official-vector comparison. I tested that value explicitly and it is inside the
broken range (row above), so `./ds4_test --logprob-vectors` on a ROCm build
should reproduce this deterministically, without needing the manual bisect. I
could not run it myself — the container ships only the `ds4*` binaries, not
`ds4_test` or `tests/`.

### On the generation-speed drop: I cannot reproduce it

Every stock build on this machine sits near 10 t/s generation:

| build | prefill | generation |
| ----- | ------- | ---------- |
| upstream 2026-07-23, fusion disabled | 5.97 | 10.03 |
| ejpir ROCm fork (built 2026-06-06), defaults | 29.3 | 9.78-10.37 |
| ejpir fork with its `FAST_FULL` preset | 37.8 | **16.11** |

So I only see ~16 t/s with that fork's non-upstream fast paths enabled (WMMA
MoE, prequantised Q8 decode matvecs, cuBLAS attention-output, f16 output
projections). I cannot say from my own data whether upstream generation
regressed between June and July — it may be that your faster run had something
enabled, or that our machines differ. Happy to run whatever would help tell
those apart.

For what it is worth, those fast paths appear not to cost quality:
`--perplexity-file` over the same 1834 scored tokens gives `avg_nll` 1.825101
with them on and 1.825690 with them off.

**Comment by jessa0** [comment]
> Here is a patch that restores speed and correctness (no guarantees as to explaining mecanisms)
> 
> [fix-rocm-regression.patch](https://github.com/user-attachments/files/30234695/fix-rocm-regression.patch)

i was previously using this patch (thank you!), but i've been running without it for a while. i suspect this issue may have been fixed on main by 1e8f16c.
